services:
    noetic_ws:
        build: dockerfile/noetic
        container_name: iiwa_phys_noetic_container
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
            # to transport X11 application window
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            - ROS_HOSTNAME=localhost
        volumes:
            # for USB devices
            - /dev:/dev
            # to tansport X11 application (require xhost local:)
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            # fonts
            - /usr/share/fonts/truetype/freefont:/usr/share/fonts/truetype/freefont
            # source codes
            - ./catkin_ws/src/iiwa_example_motion:/catkin_ws/src/iiwa_example_motion
            - ./catkin_ws/src/iiwa_description:/catkin_ws/src/iiwa_description
            - ./catkin_ws/src/iiwa_moveit_config:/catkin_ws/src/iiwa_moveit_config
            - ./scripts/isaacgym_rrt.py:/scripts/isaacgym_rrt.py
            - ./scripts/isaacgym_vis.py:/scripts/isaacgym_vis.py
            - ./scripts/isaacgym_pick.py:/scripts/isaacgym_pick.py
            - ./scripts/pybullet_rrt.py:/scripts/pybullet_rrt.py
            - ./scripts/pybullet_vis.py:/scripts/pybullet_vis.py
            - ./scripts/mujoco_vis.py:/scripts/mujoco_vis.py
            - ./scripts/genesis_hello.py:/scripts/genesis_hello.py
            - ./scripts/genesis_motion.py:/scripts/genesis_motion.py
            - ./scripts/genesis_grasp.py:/scripts/genesis_grasp.py
            # dataset
            - ./dataset/:/dataset
        privileged: true
        tty: true
        network_mode: host
        command: bash -c "source /opt/ros/noetic/setup.bash && cd /catkin_ws && catkin build -DPYTHON_EXECUTABLE=/usr/bin/python3 && bash"   
    humble_ws:
        build:
            context: dockerfile/humble
            args:
                MAKEFLAGS: -j4
                PARALLELWORKERS: 4
        container_name: iiwa_phys_humble_container
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
            # to transport X11 application window
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            - ROS_HOSTNAME=localhost
        volumes:
            # for USB devices
            - /dev:/dev
            # to tansport X11 application (require xhost local:)
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            # fonts
            - /usr/share/fonts/truetype/freefont:/usr/share/fonts/truetype/freefont
            # shared directories
            - ./yaml:/yaml
            - ./colcon_ws/src/lbr_fri_ros2_stack:/root/colcon_ws/src/lbr-stack/src/lbr_fri_ros2_stack
            # dataset
            - ./dataset/:/dataset
        privileged: true
        tty: true
        network_mode: host
        command: bash -c "source /opt/ros/humble/setup.bash && cd /root/colcon_ws && colcon build --symlink-install --parallel-workers 1 && bash"   
