# these parameters are read by the lbr_system_interface.xacro and configure the lbr_ros2_control::SystemInterface
hardware:
  fri_client_sdk: # the fri_client_sdk version is used to create the correct state interfaces lbr_system_interface.xacro
    major_version: 1
    minor_version: 15
  client_command_mode: position # the command mode specifies the user-sent commands. Available: [position, torque, wrench]
  port_id: 30200 # port id for the UDP communication. Useful in multi-robot setups
  remote_host: INADDR_ANY # the expected robot IP address. INADDR_ANY will accept any incoming connection
  rt_prio: 80 # real-time priority for the control loop
  # exponential moving average time constant for joint position commands [s]:
  #   set tau > robot sample time for more smoothing on the commands
  #   set tau << robot sample time for no smoothing on the commands
  joint_position_tau: 0.04
  command_guard_variant: default # if requested position / velocities beyond limits, CommandGuard will be triggered and shut the connection. Available: [default, safe_stop]
  # exponential moving average time constant for external joint torque measurements [s]:
  #   set tau > robot sample time for more smoothing on the external torque measurements
  #   set tau << robot sample time for no smoothing on the external torque measurements
  external_torque_tau: 0.04
  # exponential moving average time constant for joint torque measurements [s]:
  #   set tau > robot sample time for more smoothing on the raw torque measurements
  #   set tau << robot sample time for no smoothing on the raw torque measurements
  measured_torque_tau: 0.04
  # for position control, LBR works best in open_loop control mode
  # note that open_loop is overridden to false if LBR is in impedance or Cartesian impedance control mode
  open_loop: true
estimated_ft_sensor: # estimates the external force-torque from the external joint torque values
  enabled: true # whether to enable the force-torque estimation
  update_rate: 100 # update rate for the force-torque estimation [Hz] (less or equal to controller manager update rate)
  rt_prio: 30 # real-time priority for the force-torque estimation
  chain_root: lbr_link_0
  chain_tip: lbr_link_ee
  damping: 0.2 # damping factor for the pseudo-inverse of the Jacobian
  force_x_th: 2.0 # x-force threshold. Only if the force exceeds this value, the force will be considered
  force_y_th: 2.0 # y-force threshold. Only if the force exceeds this value, the force will be considered
  force_z_th: 2.0 # z-force threshold. Only if the force exceeds this value, the force will be considered
  torque_x_th: 0.5 # x-torque threshold. Only if the torque exceeds this value, the torque will be considered
  torque_y_th: 0.5 # y-torque threshold. Only if the torque exceeds this value, the torque will be considered
  torque_z_th: 0.5 # z-torque threshold. Only if the torque exceeds this value, the torque will be considered
