# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
    joint_model_group: iiwa_gripper
    joint_model_group_pose: todo_no_pose_selected
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
    loop_hz: 500
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
    joints:
        - iiwa_joint_1
        - iiwa_joint_2
        - iiwa_joint_3
        - iiwa_joint_4
        - iiwa_joint_5
        - iiwa_joint_6
        - iiwa_joint_7
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500

iiwa_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
        - iiwa_joint_1
        - iiwa_joint_2
        - iiwa_joint_3
        - iiwa_joint_4
        - iiwa_joint_5
        - iiwa_joint_6
        - iiwa_joint_7
    constraints:
        # Default is 0
        goal_time: 0.1
        # Default is 0.01, but is 0 for due to the movegroup/follow_joint_trajectory/goal tolerance is empty
        stopped_velocity_tolerance: 0
        iiwa_joint_1:
            trajectory: 0
            goal: 0.01
        iiwa_joint_2:
            trajectory: 0
            goal: 0.01
        iiwa_joint_3:
            trajectory: 0
            goal: 0.01
        iiwa_joint_4:
            trajectory: 0
            goal: 0.01
        iiwa_joint_5:
            trajectory: 0
            goal: 0.01
        iiwa_joint_6:
            trajectory: 0
            goal: 0.01
        iiwa_joint_7:
            trajectory: 0
            goal: 0.01
    gains:
        iiwa_joint_1: {p: 1000.0, i: 1.0, d: 1.0}
        iiwa_joint_2: {p: 1000.0, i: 1.0, d: 1.0}
        iiwa_joint_3: {p: 1000.0, i: 1.0, d: 1.0}
        iiwa_joint_4: {p: 1000.0, i: 1.0, d: 1.0}
        iiwa_joint_5: {p: 1000.0, i: 1.0, d: 1.0}
        iiwa_joint_6: {p: 1000.0, i: 1.0, d: 1.0}
        iiwa_joint_7: {p: 1000.0, i: 1.0, d: 1.0}

gripper_controller:
    type: "position_controllers/GripperActionController"
    joint: finger_joint
    gains:
        finger_joint: {p: 1.0, i: 0.0, d: 1.0}

controller_list:
    - name: iiwa_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: True
      joints:
        - iiwa_joint_1
        - iiwa_joint_2
        - iiwa_joint_3
        - iiwa_joint_4
        - iiwa_joint_5
        - iiwa_joint_6
        - iiwa_joint_7
    - name: gripper_controller
      action_ns: gripper_cmd
      type: GripperCommand
      default: true
      joints:
        - finger_joint
